import { useState, type FormEvent } from "react"
import type { FitnessLevel, PlanOut, TripRequestOut } from "../api/types"

export interface ClarificationAnswers {
  age: number | null
  fitness_level: FitnessLevel | null
  budget_usd: number | null
}

interface ItineraryPanelProps {
  trip: TripRequestOut
  planResult: PlanOut | null
  isLoading: boolean
  errorMessage: string | null
  onRequestPlan: () => void
  onAnswerClarification: (answers: ClarificationAnswers) => void
}

// The backend's clarifying questions are unconstrained free text generated by the planner LLM
// (see app/agent/planner.py) — there's no field-level mapping in the API. The only structured
// fields the client can answer with are age / fitness_level / budget_usd, so this form always
// offers those three, pre-filled with whatever the trip already has, and re-PATCHes + re-plans.
function ClarificationForm({
  trip,
  questions,
  onAnswerClarification,
}: {
  trip: TripRequestOut
  questions: string[]
  onAnswerClarification: (answers: ClarificationAnswers) => void
}) {
  const [age, setAge] = useState(trip.age != null ? String(trip.age) : "")
  const [fitnessLevel, setFitnessLevel] = useState<FitnessLevel | "">(trip.fitness_level ?? "")
  const [budgetUsd, setBudgetUsd] = useState(trip.budget_usd != null ? String(trip.budget_usd) : "")

  const handleSubmit = (event: FormEvent) => {
    event.preventDefault()
    onAnswerClarification({
      age: age ? Number(age) : null,
      fitness_level: fitnessLevel || null,
      budget_usd: budgetUsd ? Number(budgetUsd) : null,
    })
  }

  return (
    <div className="rounded-xl border border-amber-300 bg-amber-50 p-6">
      <h3 className="font-semibold text-amber-900">The planner needs a bit more information</h3>
      <ul className="mt-2 list-inside list-disc space-y-1 text-sm text-amber-800">
        {questions.map((question) => (
          <li key={question}>{question}</li>
        ))}
      </ul>

      <form onSubmit={handleSubmit} className="mt-4 grid grid-cols-3 gap-3">
        <label className="flex flex-col gap-1 text-sm font-medium text-amber-900">
          Age
          <input
            type="number"
            min={0}
            max={130}
            value={age}
            onChange={(event) => setAge(event.target.value)}
            className="rounded-md border border-amber-300 px-3 py-2 text-slate-900 focus:border-indigo-500 focus:outline-none"
          />
        </label>
        <label className="flex flex-col gap-1 text-sm font-medium text-amber-900">
          Fitness level
          <select
            value={fitnessLevel}
            onChange={(event) => setFitnessLevel(event.target.value as FitnessLevel | "")}
            className="rounded-md border border-amber-300 px-3 py-2 text-slate-900 focus:border-indigo-500 focus:outline-none"
          >
            <option value="">—</option>
            <option value="low">Low</option>
            <option value="moderate">Moderate</option>
            <option value="high">High</option>
          </select>
        </label>
        <label className="flex flex-col gap-1 text-sm font-medium text-amber-900">
          Budget (USD)
          <input
            type="number"
            min={0}
            value={budgetUsd}
            onChange={(event) => setBudgetUsd(event.target.value)}
            className="rounded-md border border-amber-300 px-3 py-2 text-slate-900 focus:border-indigo-500 focus:outline-none"
          />
        </label>

        <button
          type="submit"
          className="col-span-3 mt-1 rounded-md bg-amber-600 px-4 py-2 font-semibold text-white transition hover:bg-amber-700"
        >
          Submit answers and re-plan
        </button>
      </form>
    </div>
  )
}

const INTENSITY_STYLES: Record<string, string> = {
  low: "bg-emerald-100 text-emerald-800",
  moderate: "bg-amber-100 text-amber-800",
  high: "bg-rose-100 text-rose-800",
}

export function ItineraryPanel({
  trip,
  planResult,
  isLoading,
  errorMessage,
  onRequestPlan,
  onAnswerClarification,
}: ItineraryPanelProps) {
  return (
    <section className="space-y-4 rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold text-slate-900">Itinerary</h2>
        {(!planResult || planResult.status === "needs_clarification") && (
          <button
            type="button"
            onClick={onRequestPlan}
            disabled={isLoading}
            className="rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white transition hover:bg-indigo-700 disabled:cursor-not-allowed disabled:bg-slate-300"
          >
            {isLoading ? "Planning…" : planResult ? "Try planning again" : "Plan itinerary"}
          </button>
        )}
      </div>

      {errorMessage && (
        <p role="alert" className="rounded-md bg-red-50 px-3 py-2 text-sm text-red-700">
          {errorMessage}
        </p>
      )}

      {planResult?.status === "needs_clarification" && (
        <ClarificationForm
          trip={trip}
          questions={planResult.questions}
          onAnswerClarification={onAnswerClarification}
        />
      )}

      {planResult?.status === "ready" && (
        <div className="space-y-4">
          {planResult.itinerary.days.map((day) => (
            <div key={day.day_number} className="rounded-lg border border-slate-200 p-4">
              <h3 className="font-semibold text-slate-900">Day {day.day_number}</h3>
              <p className="mt-1 text-sm text-slate-600">{day.summary}</p>
              <ul className="mt-3 space-y-2">
                {day.activities.map((activity) => (
                  <li key={activity.name} className="rounded-md bg-slate-50 p-3">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="font-medium text-slate-900">{activity.name}</span>
                      <span
                        className={`rounded-full px-2 py-0.5 text-xs font-medium ${
                          INTENSITY_STYLES[activity.intensity.toLowerCase()] ?? "bg-slate-200 text-slate-700"
                        }`}
                      >
                        {activity.intensity}
                      </span>
                    </div>
                    <p className="mt-1 text-sm text-slate-600">{activity.description}</p>
                    <a
                      href={activity.source_url}
                      target="_blank"
                      rel="noreferrer"
                      className="mt-1 inline-block text-xs text-indigo-600 hover:underline"
                    >
                      Source
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      )}

      {!planResult && !isLoading && (
        <p className="text-sm text-slate-500">Run the planner to generate a day-by-day itinerary.</p>
      )}
    </section>
  )
}
