"""initial schema

Revision ID: d8a61532fcf4
Revises: 
Create Date: 2026-07-20 19:36:24.136042
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = 'd8a61532fcf4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_anonymized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=True)
    op.create_table('trip_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('destination', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('destination_airport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('depart_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('return_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('fitness_level', sa.Enum('LOW', 'MODERATE', 'HIGH', name='fitnesslevel'), nullable=True),
    sa.Column('budget_usd', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'FLIGHTS_SEARCHED', 'ITINERARY_READY', name='tripstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_request_user_id'), 'trip_request', ['user_id'], unique=False)
    op.create_table('agent_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_request_id', sa.Integer(), nullable=False),
    sa.Column('dbos_workflow_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_ms', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_request_id'], ['trip_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_trip_request_id'), 'agent_run', ['trip_request_id'], unique=False)
    op.create_table('execution_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_request_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('API_CALL', 'DB_QUERY', 'PROTOCOL', 'HITL', name='executioneventkind'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_request_id'], ['trip_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_event_trip_request_id'), 'execution_event', ['trip_request_id'], unique=False)
    op.create_table('flight_search_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_request_id', sa.Integer(), nullable=False),
    sa.Column('offer_index', sa.Integer(), nullable=False),
    sa.Column('carrier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('depart_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('arrive_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stops', sa.Integer(), nullable=False),
    sa.Column('booking_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_offer', sa.JSON(), nullable=True),
    sa.Column('source', sa.Enum('LIVE', 'CACHED', name='flightresultsource'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_request_id'], ['trip_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_search_result_trip_request_id'), 'flight_search_result', ['trip_request_id'], unique=False)
    op.create_table('itinerary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_request_id', sa.Integer(), nullable=False),
    sa.Column('days', sa.JSON(), nullable=True),
    sa.Column('generated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_request_id'], ['trip_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_request_id', name='uq_itinerary_trip_request')
    )
    op.create_index(op.f('ix_itinerary_trip_request_id'), 'itinerary', ['trip_request_id'], unique=False)
    op.create_table('agent_run_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('MODEL', 'TOOL', name='agentstepkind'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_step_agent_run_id'), 'agent_run_step', ['agent_run_id'], unique=False)
    op.create_table('hitl_booking_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_request_id', sa.Integer(), nullable=False),
    sa.Column('flight_search_result_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('PENDING_USER_CONFIRMATION', 'CONFIRMED', 'EXECUTED', 'CANCELLED', 'EXPIRED', name='bookingstate'), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('booking_options', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flight_search_result_id'], ['flight_search_result.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['trip_request_id'], ['trip_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_request_id', 'flight_search_result_id', name='uq_booking_trip_flight')
    )
    op.create_index(op.f('ix_hitl_booking_log_flight_search_result_id'), 'hitl_booking_log', ['flight_search_result_id'], unique=False)
    op.create_index(op.f('ix_hitl_booking_log_state'), 'hitl_booking_log', ['state'], unique=False)
    op.create_index(op.f('ix_hitl_booking_log_trip_request_id'), 'hitl_booking_log', ['trip_request_id'], unique=False)
    op.create_table('booking_transition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_log_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.Enum('PENDING_USER_CONFIRMATION', 'CONFIRMED', 'EXECUTED', 'CANCELLED', 'EXPIRED', name='bookingstate'), nullable=False),
    sa.Column('to_state', sa.Enum('PENDING_USER_CONFIRMATION', 'CONFIRMED', 'EXECUTED', 'CANCELLED', 'EXPIRED', name='bookingstate'), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['booking_log_id'], ['hitl_booking_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_transition_booking_log_id'), 'booking_transition', ['booking_log_id'], unique=False)
    # ### end Alembic commands ###

    # Append-only enforcement, in the DATABASE — not app discipline. A BEFORE UPDATE OR DELETE
    # trigger on each audit table raises an exception, so no application code path (and no agent)
    # can ever mutate or erase an audit row once it is written. This is the physical enforcement
    # point behind the HITL "who approved what, when" guarantee.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION reject_audit_row_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'table % is append-only: % is not permitted (row id=%)',
                TG_TABLE_NAME, TG_OP, OLD.id
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for audit_table in ("booking_transition", "execution_event"):
        op.execute(
            f"""
            CREATE TRIGGER {audit_table}_is_append_only
                BEFORE UPDATE OR DELETE ON {audit_table}
                FOR EACH ROW EXECUTE FUNCTION reject_audit_row_mutation();
            """
        )


def downgrade() -> None:
    for audit_table in ("booking_transition", "execution_event"):
        op.execute(f"DROP TRIGGER IF EXISTS {audit_table}_is_append_only ON {audit_table};")
    op.execute("DROP FUNCTION IF EXISTS reject_audit_row_mutation();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_transition_booking_log_id'), table_name='booking_transition')
    op.drop_table('booking_transition')
    op.drop_index(op.f('ix_hitl_booking_log_trip_request_id'), table_name='hitl_booking_log')
    op.drop_index(op.f('ix_hitl_booking_log_state'), table_name='hitl_booking_log')
    op.drop_index(op.f('ix_hitl_booking_log_flight_search_result_id'), table_name='hitl_booking_log')
    op.drop_table('hitl_booking_log')
    op.drop_index(op.f('ix_agent_run_step_agent_run_id'), table_name='agent_run_step')
    op.drop_table('agent_run_step')
    op.drop_index(op.f('ix_itinerary_trip_request_id'), table_name='itinerary')
    op.drop_table('itinerary')
    op.drop_index(op.f('ix_flight_search_result_trip_request_id'), table_name='flight_search_result')
    op.drop_table('flight_search_result')
    op.drop_index(op.f('ix_execution_event_trip_request_id'), table_name='execution_event')
    op.drop_table('execution_event')
    op.drop_index(op.f('ix_agent_run_trip_request_id'), table_name='agent_run')
    op.drop_table('agent_run')
    op.drop_index(op.f('ix_trip_request_user_id'), table_name='trip_request')
    op.drop_table('trip_request')
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.drop_table('user_account')
    # ### end Alembic commands ###
